### ISSUE TITLE
release more frequently

### ISSUE THREAD

**Issue by vecpeng** [ViroCommunity/viro#110]
Hi, thanks for your awesome library, I really like viro but could it releases more frequently? Maybe it can be released more frequently like expo and react-native?
Now it just released every three months or even half year and I can't try the latest feature, which helps me a lot.
Maybe a big version can be devided into some little versions?

**Comment by robertjcolley** [comment]
I've been trying to get the docs 100% situated, since there is a lot of bad formatting still. See the pinned GitHub issue. I've recently taken a new job, so I've been busy.

I'm thinking of doing a release with Expo, TypeScript and bitcode support. I was shooting to have GVR on iOS in this release as well, but I'd rather get out expo support

Thank you all for being patient! Life is getting in the way here.

Contributions are welcome!
