### ISSUE TITLE
Viro 2.21.1

### ISSUE THREAD

**Issue by Cchumi** [ViroCommunity/viro#56]
Hi it's not a pure issue but I investigate to find out why the 2.21.1 release is not working and show UIManager error for all the viro components.

I find the culprite..

I download the zip of 2.21.0 and 2.21.1 and find that for IOS libviroreact.a is not the good one.
The size of the package is not relevant for the lib.

![image](https://user-images.githubusercontent.com/40697701/136926566-54a0bdbe-c992-4bd4-9341-5cd87dbffa0b.png)

If I check the same file on the 2.21.0 release this file is bigger

![image](https://user-images.githubusercontent.com/40697701/136926773-fb63b262-614a-4695-909d-af34b4bac57d.png)

So I take all the libviroreact.a from 2.21.0 folder and paste it in my node module viro react. 

I compile from xCode and now my app doesn't complain anymore for VRTText not found in UIManager.
And work as expected.

How can I build this libviroreact.a from my side ?

Hope this could give you the right way to fix that.

Cchumi

**Comment by ovy9086** [comment]
Downgrading to 2.20 solved this issue. so it seems something is wrong with 2.21 ? 🤔

**Comment by keithvongola** [comment]
Will there be a new release for the fix? 2.20 is not working on my android project

**Comment by doranteseduardo** [comment]
Hello,
Yes, I have scheduled a release for this Nov 28 (Sunday)

**Comment by doranteseduardo** [comment]
Just to get you all in context.
The issue came into scene as we are unable to rebuild the static_lib variant of Viro.

Last time, when we made some changes to the iOS native side we were only able to build the library but the mentioned variant.

The static_lib has too many issues due the way the GVR was striped out.

So in the next release it will be removed, solving all this linking problems.

**Comment by Cchumi** [comment]
Great news Ed you are welcome 🙏

**Comment by doranteseduardo** [comment]
The fix is ready, however I'd appreciate if you help testing out!
I'm about to upload an update and I need your help to test the iOS side just to be sure it's working as expected.

- Install viro normally, then download this:
https://drive.google.com/file/d/1KDGjqWbjFqh4dQeCyiV2Le9VqXKRttmt/view?usp=sharing

- Put its contents in the corresponding path in node_modules.

- Modify your Podfile, replace this:
pod 'ViroKit_static_lib', :path => '../node_modules/@viro-community/react-viro/ios/dist/ViroRenderer/static_lib'

with this:
pod 'ViroKit', :path => '../node_modules/@viro-community/react-viro/ios/dist/ViroRenderer/'

- Run "pod install" in the ios folder.

- Run your app.

You should not have any issue on iOS anymore and also, ViroVideo must be working again.

I'd appreciate your feedback, if this test goes well it will be deployed into npm soon.

Thanks in advance!

**Comment by Cchumi** [comment]
Hi I just test it in my own app and it is working without any issue for the moment. 

I just try also in starter kit and it is working as expected. 

No more UIManager error.

Nice job :)


I will give a try on android in these days to see if it is also working.

**Comment by doranteseduardo** [comment]
I'm working on some changes repository-level (due lfs) to publish this as soon as possible.

**Comment by doranteseduardo** [comment]
[v2.22.0 ](https://www.npmjs.com/package/@viro-community/react-viro) is not in NPM and it fixes the iOS issues.
Thank you all for your time and support!

Note:
We have issues on Github so the latest changes and the release may take few days to hit here.
