### ISSUE TITLE
Viromedia/viro issues

### ISSUE THREAD

**Issue by robertjcolley** [ViroCommunity/viro#71]
Documenting the process of replicating, triaging, migrating, and resolving the existing issues in https://github.com/viromedia/viro to this repository.

## viromedia/viro Issue Plan:
1. Triage issue (bug, feature request, etc.)
2. If issue is a bug with Viro, attempt to replicate issue in https://github.com/NS-BOBBY-C/starter-kit using latest community version
  1. If issue is replicated, create new ViroCommunity issue for bug
  2. If issue is not replicated, close issue with comment forwarding OP to ViroCommunity fork
3. Create issue in ViroCommunity/viro
4. Put issue on roadmap for community development

## Progress
2021-12-22: 362 outstanding issues

**Comment by weex** [comment]
As a maintainer of a couple of open source forks, I think the best course of action is actually to let people create issues as they find them in ViroCommunity. With the fork you have a clean slate and I think it's going to much more fun and productive for this community to build its own backlog vs starting with those 362 issues of varying staleness.

That being said, if you know of some outstanding problems, by all means create issues and link to the previous ones so that history can be put to use.

**Comment by robertjcolley** [comment]
After giving this some thought, I agree. There is enough work without inheriting 300+ issues. Closing and unpinning.
